### ISSUE TITLE
Can't use any consumable items from the bags.

### ISSUE THREAD

**Issue by Kaybris** [GoldpawsStuff/AzeriteUI#10]
When trying to use e.g food item from the bag an error pops up saying "AzeriteUI has been blocked from an action available only to BlizzardUI." I have to put my consumable items on the action bar to be able to use them.

**Comment by Goldpaw** [comment]
that is part of the neverending taint resulting from addons not getting along with the 10.0.2 editmode. 

I cleared a boatload of problems in 4.0.16, and to my knowledge this problem is fixed there. Be warned though, that taints and blocked actions aren't bugs, they are notices of discovery. If another addon taints the editmode azeriteui still might get the blame. 

the way the editmode works is that anything that taints it taints the editmode. the editmode in turn taints everything else. then the first addon to use a tainted object after that, gets the blame.
