### ISSUE TITLE
TotalRoleplay3 and Azerite UI unit tooltip conflict.

### ISSUE THREAD

**Issue by Autumnbrook** [GoldpawsStuff/AzeriteUI#130]
**What WoW version do you wish to see this feature in?**
- [ ] Classic Era
- [ ] Burning Crusade Classic
- [X] Shadowlands

**Is your feature request related to a problem? Please describe.**
when you hover over yourself using TRP3, your character's full name gets added to the tooltip. Ex: 
![image](https://user-images.githubusercontent.com/104316286/164986154-1cbfb9d3-e871-4d43-8d92-a2a3cb2a6c2a.png)
but with Azerite UI enabled, a conflict happens over this and this occurs: Ex:
![image](https://user-images.githubusercontent.com/104316286/164986226-362f4163-3dc6-4f4a-a88f-eed645647063.png)
this ONLY happens when you hover over yourself, and not any other player.

**Describe the solution you'd like**
if possible, i'd like my character's full names to be shown in the tooltip.

**Describe alternatives you've considered**
I have tried a few different plating addons to work around this and none have given me the solution i was looking for.
KuiNameplates and RP Tags

**Comment by Goldpaw** [comment]
I'm trying out a solution that reverts to regular (but styled) GameTooltips for all unitframes when totalRP3 is enabled. 

Should be included in 3.2.527-Alpha on CurseForge (available by clicking "View All" on the file page or enabling Alpha/Beta builds from the addon's right-click menu in the CurseForge app), or from the latest git version here on GitHub. 

I haven't tested the code, because I can't. Which is why I'm leaving it as an alpha version until somebody can verify that it works, is syntax bug free, and did what we intended. Then I'll push it out as a main release! :)

**Comment by Autumnbrook** [comment]
i've tried both 3.2.527-Alpha and 3.2.529-Alpha and both threw up 17 pages of LUA warnings. i don't know how useful it is, but i've pasted it all, separated by page, in this bin. https://ghostbin.com/SHVFT

**Comment by Autumnbrook** [comment]
well, so far it seems to be a success! 
![image](https://user-images.githubusercontent.com/104316286/165667278-4a5b5dd4-405c-46f7-af9d-bea22602e837.png)
there is this weird overlapping tooltip issue i ran into after hovering over the health bar and then an ability, but that's probably something i need to tweak in TRP. 
![image](https://user-images.githubusercontent.com/104316286/165667527-8505e81d-81a1-488d-808a-17bb22cae4cc.png)

**Comment by Goldpaw** [comment]
I can see the reason. My widgets for displaying auras and stuff, they use the unitframe tooltip too. And they expected the special AzeriteUI one, not the standard GameTooltip.

I changed the change to only using the standard blizzard tooltip for normal unit mouseover, and still use the AzeriteUI tooltips for auras and things like that. 

In theory that should solve it. :)
