### ISSUE TITLE
[MACINTOSH] Settings are locked behind middle mouse.

### ISSUE THREAD

**Issue by DevDurs** [GoldpawsStuff/AzeriteUI#140]
Mac trackpads do not possess middle mouse click functionality. With M1 compatibility WoW is now M1 native, but there is simply no way to enter the AzeriteUI settings without middle mouse.

This would be easily rectified by adding a /command to open the settings.

**Comment by Goldpaw** [comment]
/commands are insecure and would break the menu's ability to toggle actionbars and unitframes in combat, which is why I haven't added one. 

There are however a keybind. Open blizzard's keybind interface, go to the addons section at the bottom, find AzeriteUI, and bind the button to open the menu to something. 

Voila! :)
