### ISSUE TITLE
Vehicle action bar not working directly with Bartender4

### ISSUE THREAD

**Issue by PanterLock** [GoldpawsStuff/AzeriteUI#141]
## Vehicle action bar not working directly
When I enter a vehicle, my action bar keybinds do not respond.
For example, on the fight with Devos in SoA where I need to throw the spear, the keybind is 1, but when I press it it doesn't respond. 
However, this can be fixed by reloading UI. After reloading UI, it is responsive again.
  
### What game version(s) does it happen in? Choose your version and the highest expansion you own. 
9.2.5 (44325)
- Live Realms
	- [ ] Shadowlands 

### What addon theme(s) does it happen in?  

- [ ] Azerite 
- [ ] Legacy

### Does this happen with ONLY this addon enabled?  

- [ ] No 
I think this is a addon conflict. When I disable Bartender4, the issues is resolved.

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Monk 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  
No

### Steps to reproduce  
Have Bartender4 loaded. I do not have anything keybinding in Bartender to override the Blizzard bars. I have Bar 1 disabled in Bartender.
Use the BFA WQ "Beachhead", in either UI, with Bartender4 loaded.

### Expected behaviour  
When you start the WQ and your action bar 1 changes to the vehicle bar, pressing 1 does not respond and you don't shoot the magic balls.

### Actual behaviour  
Expected behaviour happens with bartender enable. Expected behaviour does not happen with Bartender4 disabled.

**Comment by Goldpaw** [comment]
There's an option somewhere in the bartender menu that enables or disables the blizzard vehicle bar. 

If the blizzard vehicle bar is set to enabled, bartender hands the keybinds back to the blizzard bar when entering a vehicle. This cause MY bar not to react to those keybinds. 

So that option in bartender has to be disabled, and everything should work fine, with the AzeriteUI vehicle bar once again reaction to both mouse clicks and keybinds. 

Also, if you're using ConsolePort, that option will be enabled in bartender (by ConsolePort) by default, and has to be disabled from within ConsolePort as well. Don't ask me where, I have no clue, I just know this happens after discussions about the issue on discord, in the patron zone.
