### ISSUE TITLE
How to replace equipped bags?

### ISSUE THREAD

**Issue by tenub** [GoldpawsStuff/AzeriteUI#143]
I looked through all of the options to no avail.

**Comment by Goldpaw** [comment]
The bag buttons are shown at the bottom of the default blizzard backpack in azeriteui, and should for the most part work as they normally do in the default blizzard interface. If that for some reason bugs out, the fix is usually to get to some safe place with no combat, do a /reload and then swap bags before any combat starts again. 

If you're using another bag addon like bagnon, you'll have to use the bag buttons in that one to replace them. If you're using a bag addon with no bag bar, you'll have to temporarily disable that or azeriteui to do it.

**Comment by tenub** [comment]
It seems I must disable this addon to get access to the bags bar. Here is a screenshot with all bags open:
![bags](https://user-images.githubusercontent.com/1896007/180676649-4bcfa6bf-a6a4-42df-8d1d-5e1e9de214e4.png)

Is it possible to see how it should look?

**Comment by Goldpaw** [comment]
It shouls look like that, but with the 4 bag slots glued to the bottom of the main backpack frame. 

Are you using bartender or something, with its bag bar enabled?

**Comment by tenub** [comment]
Azerite UI is the only addon. I am however playing TBC Classic.

**Comment by rebbo-cop** [comment]
I'm having the same issue - had to disable AzeriteUI to replace a bag. The other AddOns I'm using are Immersion, Questie and OPie (but same issue occurs with those disabled)

**Comment by Goldpaw** [comment]
Wait for the most recent version (3.2.555-RC or higher) to beccome available on CurseForge, or download it from Wago. The bag buttons are attached to the backpack frame there.
