### ISSUE TITLE
About minimap button

### ISSUE THREAD

**Issue by JasonQWJ** [GoldpawsStuff/AzeriteUI#17]
![无标题](https://user-images.githubusercontent.com/18637996/90351366-a48fc300-e072-11ea-9afb-87fe29af5853.png)
These buttons went to the back in  wow classic.

**Comment by goldpaw** [comment]
Well, first of all, if I was to do something with this, I would just hide the buttons, not move them to the front. We don't want minimap buttons in this UI. 

Second, this isn't a bug, because there is no error text, and AzeriteUI didn't make those buttons. Some other addon which you haven't listed does that. I need to know which addons those buttons belong to if I am to do anything about them. And what I would do is just to hide them, which I don't think is what you're after here. 

So I recommend Minimap Button Bag to handle Minimap buttons. We link it on the download page too:
https://www.curseforge.com/wow/addons/mbb-classic
