### ISSUE TITLE
Target castbar (healthbar) not cancelled when interrupted

### ISSUE THREAD

**Issue by torhaala** [GoldpawsStuff/AzeriteUI#4]
**What WoW version do you wish to see this feature in?**
- [x] Classic
- [ ] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
When a mob/players casts a spell, which is interrupted by for example pummel, the cast bar overlay (on hp bar) continues to count down as if not interrupt was cast or it failed.

**Describe the solution you'd like**
Cast bar stop/cancel on successful interrupts or cancelled casts.

**Comment by goldpaw** [comment]
Sometimes the classic cast interrupts simply aren't fully detected. This is because of how the client reports enemy casts, which is "not at all". We use a 3rd party library to detect casts and interrupts, and this in turn is based in info available in the combat lag. Which isn't all we always need. 

So this will simply sometimes be glitchy in classic. Or until blizzard one day decides to add back enemy casts into the API and event system.
