### ISSUE TITLE
Covenant Sanctum Ability on Minimap

### ISSUE THREAD

**Issue by Bashadash** [GoldpawsStuff/AzeriteUI#52]
## The problem  
Covenant Sanctum button on minimap is not available, or easily found if it is

### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [ ] Retail 
	- [ ] Battle for Azeroth
	- [x] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with NO other addons enabled?  

- [ ] Yes 
- [x] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [x] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [x] Shaman 
- [ ] Warlock 
- [ ] Warrior

**Comment by goldpaw** [comment]
Something not there when it comes to the minimap isn't a bug, but technically speaking a feature request. So I'm listing it as one.

**Comment by Bashadash** [comment]
Thank you. I was not sure if a bug was blocking it or not. I realized after
submission that it might be a feature request, i just wasnt able to get
back to the ticket yet to update.

**Comment by pauldcox** [comment]
This is kind of a big feature to be missing in retail since it's been a part of every expansion since WoD so I have no idea why it isn't implemented yet.

In the meantime, for anyone that wants to access their covenant tab, you can make a macro containing `/run ShowGarrisonLandingPage()` which will make it open. If you've never run a script before, you'll get a popup asking for permission. After clicking "accept," the macro will work from then on.

**Comment by goldpaw** [comment]
Or just keybind it from blizzard's keybind interface, which also has been a part of the game for many expansions. It's named "Toggle Garrison Report" and located at the bottom of Key Bindings > Interfac Panel.

As to why it hasn't been implemented yet, the answer is simple: I never use it, nor do my co-designer. So why would we prioritize it? In general we want as few buttons as possible, that's the idea of the UI. 

It's on my todo-list, but so are other things of higher importance to me and mine. I remind everybody I do not work for blizzard, this is not an official part of the game. It's an unpaid fan project, made by private gamers. So our priorities align with how we play the game, not how others do. 

I've been using the keybind myself since WoD. Works like a charm! :)

![WoWScrnShot_020921_112641](https://user-images.githubusercontent.com/6476535/107350409-b1451f00-6ac9-11eb-907e-5aad037011f1.jpg)

**Comment by pauldcox** [comment]
I honestly never knew that keybind existed until now. 😮  Now I feel like an idiot. 🤣 

I didn't mean any offense, I know you do this on your own time and I really appreciate it. Took me some time to adjust to it, but now I love it. Especially great on classic where it basically includes a lot of other things you would normally need other addons for there.

Thanks for your work! 👍

**Comment by Bashadash** [comment]
Thank you for the emails and insight on this. Unfortunately, I have
switched to a different ui that accommodates more atm. Hopefully, I can get
back to azerite up, as I really loved using it at the end of bfa.

**Comment by goldpaw** [comment]
On a second thought, let's NOT add this. The keybind is much more preferable, keeps the UI cleaner, and enforces more player interaction with the game, which is the playstyle we wish to encourage.
