### ISSUE TITLE
I saw where it said that a menu will be added later..

### ISSUE THREAD

**Issue by OGAscension** [GoldpawsStuff/AzeriteUI#83]
--I play Classic Wow, for the sole purpose of transitioning into TBC Classic.
It is my hope that there will be TBC Legacy servers even once Wrath Classic and other versions of the game become public.

My issue is that I can not access any of my mini map buttons with either setup.
I need to be able to move the mini map where I want it.

--Minor bug with the chat log, where it is at the bottom left of the screen and then it is about 25% further up the screen seemingly randomly.
-Recommend making the channels viewable before scroll over. Like I have General/Trade/Guild/Whisper all on one "page", then Combat Log, and LFG channels on separate tabs. Seeing which channel I want to change to and where the button is without having to move the mouse around trying to find it so that it will be displayed would be beneficial.

--Similar issue to the mini map, The Player UI and Target UI are in places where I have action bars (Using Bartender4), and though I could move those bars, I like them where they are and would like to be able to move some of your UI around to suite my desired UI setup.

**Awesome work. Your UI is super clean, and I love the graphics.
A bit more utility/customization and I think you guys can drop the beta, and call it the full version. Looking forward to seeing your content releases.

---------------------------|---------------------------|---------------------------|-----------------------
---------------------------|-------------------| Add-ons I use |------------------|-----------------------
---------------------------|---------------------------|---------------------------|-----------------------
I am not a minimalist when  it comes to addons. I have many. I see it this way--if it makes my experience easier, and it helps me, I want to use it. 
My Addons include:
(ArcHUD3 Classic, AtlasLoot Classic, Auctioneer, Bagnon, Bartender, BetterVendorPrice, BiS Tracker2020, Details, Enchantrix, Extended Character Stats2.7.2, Gathermate2, Grid2, Guild Roster Manager, Informant, Leatrix Maps, Leatrix Plus, Mik's Scrolling Battle Text, Nova World Buffs, Recount, ThreatClassic2, Zpearl* Which I may be replacing with your UI If I can get it the way I want it. I used Pitbull Unit Frames about 11 years ago, and they worked well for me..) (Continuing list of Addons: AzeriteUI 3.1 Beta **Disabled until I can make it work with what I have..  Character Stats Classic, TradeSkillMaster, Speedy AutoLoot, Deadly Boss Mods, Questie.)

There is another one I have been looking for and not found-- gonna refer back to my older pc for it.   

What it does that I want is when you click on a recipe/pattern etc It tells you all of your characters that have that profession, what skill that characters profession is, if they already have it learned, if they can learn it, and more.  Very helpful when trying to acquire patterns for alts. (Mostly dealing with leveling all my alts cooking atm)

**Comment by goldpaw** [comment]
Thanks for the report, but no bugs here. 

Right-click the cogwheel in the bottom right corner of the screen, and the menu popping up represents the micro menu. Everything is there. 

As for the chat, that is a setting in the azeriteui menu, found by middle-clicking the same cogwheel. Can't remember right here and now if the setting controling the chat window movement is under the Explorer Mode submenu or Chat submenu, but it is one of them. The idea is that when in "Explorer Mode" as we call it, when the player frame fades out because you're out of combat, full health and not have any debuffs running nor targeting anything, the chat will move down to the now empty corner, instead of hovering in the middle of the screen. When hovering over that area, the player frame will become visible and the chat move up again, and if you keep your mouse over the chat window, it will remain in its default position until you move the mouse away again. 

And as mentioned, you can disable this from our middle-click menu, and have the chat always remain in the middle position if you so choose. :) 

I advise you to check out that cogwheel button and see what options are available there. Hope this helps!

**Comment by goldpaw** [comment]
Oh, and when it comes to chat channels and tabs, we do not affect those. Only the position of the primary frame. If you wish to add other tabs, change channels and message groups, that is all done the default way by right-click the header/tab of the main frame (visible when mousing over the chat) to add more, or the header/tab of any chat window to select channels and messages visible in them.
